### ISSUE TITLE
Quantifiedcode now open-source

### ISSUE THREAD

**Issue by ElieGouzien** [mre/awesome-static-analysis#139]
Hi,

It seems [quantifiedcode](https://www.quantifiedcode.com/download) is now open-source. Also I'm not sure it's really maintained.

**Comment by mre** [comment]
You are right. Thanks for the notification. 👍
Removed the copyright badge. It's using BSD and MIT licenses for the subprojects.

I'm not sure if it's maintained either, but I think it's valuable to keep it in the list, because it should still work and provide a lot of insights into a codebase. Also, it's one of the few free code-analysis web-services out there.

Thanks again for your hint. 🌈
