### ISSUE TITLE
Linter for Make files

### ISSUE THREAD

**Issue by andygrunwald** [mre/awesome-static-analysis#34]
Checkout https://github.com/mrtazz/checkmake

I wonder in which category this tool will fall ?

**Comment by mre** [comment]
To be honest, I have no clue.

Some options come to mind:
- A separate "Makefile" category -> Probably too short-sighted. We'd have to create different categories for similar tools.
- A linter category -> A very generic definition, but could confuse new visitors who don't know the exact definition of "linting" and search for such tools in a different category
- A "build tools" category -> Could be a good trade-off between the two.

Since there might be no optimal solution, I leave the final decision up to you, but I'd suggest the "build tools" category. We can always refactor later if there's too many tools (which would be a good thing).

**Comment by andygrunwald** [comment]
Thanks for feedback.
See #35
